### ISSUE TITLE
is this working or work in progress?

### ISSUE THREAD

**Issue by parveshh** [gherking/gherkin-formatter#3]
I tried using the library but i am just getting a stringified JSON of the document object, going through "gherkin-ast" the code i do not see and implementation/overriding to "toString" to correctly create a formatted string?

**Comment by szikszail** [comment]
@parveshh sorry for the late response. Yes, it is still WIP, all GherKing packages will be live with the v1.0.0.  We are on it :)

**Comment by szikszail** [comment]
@parveshh, the new version of gherking and gherkin-formatter have been released recently. You can check the latest versions and state of the releases for the precompilers on the main page of our organization: https://github.com/gherking

Please do not hesitate to reach out to us if you have any questions!
